id: P4DDA9859
initial_creation_type: input
source_metadata:
  Title: Sarahapādasya dohākoṣaḥ
  Editor: P. C. Bagchi
  Publisher: Metropolitan Printing and Publishing House Limited
  Place of Publication: Calcutta
  Year: '1838'
  Sarahapādasya dohākoṣaḥ:
    Text Version: Romanized
    Input Personnel: Bibek Shakya
    Input Date: '2015'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:58:12.853602'
last_modified_at: '2022-03-08T16:58:12.853611'
